server:
  port: ${PORT:8083}
spring:
  config:
    import: optional:configserver:http://localhost:8888/
  application:
    name : subscription-service #nome para ele reconhecer qual arquivo ele vai buscar no servidor de config
